### ISSUE TITLE
Upload doesnt work

### ISSUE THREAD

**Issue by palevoo** [Chainers/steepshot-web#40]
Upload doesnt seem to work, returns to empty profile page, with message (shown on pic) 2 attempts were taken over the course of 24 hours.
<img width="818" alt="screen shot 2017-11-03 at 10 05 27" src="https://user-images.githubusercontent.com/21197100/32366576-f346c8c0-c07e-11e7-8e55-9613bf615f17.png">

**Comment by EgorKazachenko** [comment]
@palevoo may be your posts have a low rating or adult content? Try changing the settings. If it does not help, we'll try to find the cause and fix it :)

**Comment by pmartynov** [comment]
@palevoo what's your username on Steem?

**Comment by palevoo** [comment]
its all good with new update;)
