### ISSUE TITLE
Sign in page still shown while already signed in

### ISSUE THREAD

**Issue by singhpratyush** [Chainers/steepshot-web#68]
![screenshot from 2018-01-22 12-11-59](https://user-images.githubusercontent.com/10860278/35208278-85b954c0-ff6d-11e7-8627-0c2e99e43cde.png)

**Comment by pmartynov** [comment]
Steps to reproduce:

1. Login to https://alpha.steepshot.io/
2. Type https://alpha.steepshot.io/signin in browser address bar and press Enter
3. As a result you can see the picture above.

@singhpratyush thanks for tracking this issue. What is the expected result? Should the logged in user be redirected somewhere?

**Comment by singhpratyush** [comment]
Hi @pmartynov,

I think that the user should be redirected somewhere, maybe at `/` (or ultimately at `/feed`).
